config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :home, only: [:index] do
    member do
      get 'report_back'
      post 'report_back', to: 'home#report_submit', as: 'report_submit'

      get 'request_map_assignment'
      get 'request_assignment', to: 'home#pamphlet_effort', as: 'pamphlet_effort'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/effort_state.rb
class EffortState
  include Mongoid::Document
  field :name, type: String
end

app/models/pamphlet_effort.rb
class PamphletEffort
  include Mongoid::Document
  field :reportBack, type: String
  field :pollingAreaId, type: String

  belongs_to :user

  #field :volunteer, type: Reference
  #field :pollingArea, type: Reference
  #field :state, type: Reference
end

app/models/polling_area_state.rb
class PollingAreaState
  include Mongoid::Document
  field :name, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :name,              type: String
  field :isOrganizer, type: Boolean, default: false
  field :enable,              type: Boolean, default: true
  field :can_create_event, type: Boolean, default: true
  field :phone_number, type: String
  field :city, type: String

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  layout :layout_by_resource

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :city, :email, :password ])
  end

  def after_sign_in_path_for(resource_or_scope)
    home_index_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  MAP_SOFTWARE_PORT = 8000
  MAP_SOFTWARE_HOST = 'localhost'

  before_action :authenticate_user!

  def index
  end

  def report_back
    @location_options = options_for_select(["Kanata", "Barrhaven", "Orleans", "Centertown"])
  end

  def report_submit
    # pamphlet_effort = (PamphletEffort.find_by user_id: current_user.id)&.first
    pamphlet_effort = false
    return redirect_to home_index_path, flash: { error: "You don't have an assigned polling area to report about." } unless pamphlet_effort

    pamphlet_effort.update_attribute(reportBack: params[:notes])

    redirect_to home_index_path, flash: { notice: 'Your report has been sent.' }
  end

  def request_map_assignment
    URI uri = URI::HTTP.build({
                         host: HomeController::MAP_SOFTWARE_HOST,
                         port: HomeController::MAP_SOFTWARE_PORT,
                         path: '/assign.html',
                         query: "user_id=#{current_user.id}&file_name=output.geojson"
                     })

    redirect_to uri.to_s
  end

  def pamphlet_effort

        if not params[:test].nil?
            render :inline => "<%= #{params.to_s} %>"
            return
        end
        
        pollingArea = params[:unique_polling_id]
        volunteerId          = params[:user_id]

        v = User.find(volunteerId)


        v or raise "Volunteer not found!"
        puts "Found #{v}"
        
        pe = PamphletEffort.new(
            pollingAreaId:  pollingArea,
            user: v
        )

        pe.save!

		puts "Success!!! Redirecting...."

        #http://54.145.123.77/printable.html?file_name=output.geojson&pod_id=115719

    	URI uri = URI::HTTP.build({
        	host: HomeController::MAP_SOFTWARE_HOST,
            port: HomeController::MAP_SOFTWARE_PORT,
            path: '/printable.html',
            query: "file_name=output.geojson&pod_id=#{pollingArea}" #"unique_polling_id=#{pollingArea}"
        })

    	redirect_to uri.to_s


  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    request_map_assignment_home_path(resource.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
Welcome to Artemis Prime.

app/views/home/report_back.html.erb
<div class="container" style="margin-top: 12%;">
  <h2 style="text-align: center"> Report After Completed Canvassing</h2>

 <div class="text-center">
  <%= form_tag report_submit_home_path, method: :post do %>

      <div class="field">
        <%= label_tag :notes %><br />
        <%= text_field_tag :notes %>
      </div>

       <br>

      <div class="actions">
        <%= submit_tag "Submit", class: 'btn-primary' %>
      </div>
  <% end %>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtemisPrime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#"><b>Artemis</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#"><%= link_to 'Home', home_index_path, class: "nav-link"%> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><%= link_to 'Report Back', report_back_home_path(current_user.id), class: "nav-link" %></a>
        </li>
        <li class="nav-item pull-right">
          <a class="nav-link" href="#"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete,
                                                   :class => "nav-link" %></a>
        </li>
      </ul>
    </div>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArtemisPrime</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>